Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'mattn/webapi-vim' "Required by gist
Plugin 'mattn/gist-vim'
Plugin 'chase/vim-ansible-yaml'
Plugin 'vim-scripts/scratch.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-unimpaired'
Plugin 'mileszs/ack.vim'
