;;; personal.el --- Autogenerated customization to take away scrolls etc

;;; Commentary:

;;; Code:
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))

;;; Set Ido mode
(require 'ido)
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)
;Setting up smex
(smex-initialize)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
;; This is your old M-x.
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)

;Enabels emacs to find my path variable for mac
(exec-path-from-shell-initialize)

;; Set max with to 80
(require 'whitespace)
(setq whitespace-style '(face empty tabs lines-tail trailing))
(global-whitespace-mode t)

;; Better word wrapping
(visual-line-mode 1)

;disables startsccreen
(setq inhibit-splash-screen t
      inhibit-startup-echo-area-message t
      inhibit-startup-message t)

;; Set global relative linum
;;(global-linum-mode t)
(add-hook 'haskell-mode-hook 'linum-mode)
(add-hook 'text-mode-hook 'linum-mode)
(add-hook 'fundamental-mode-hook 'linum-mode)
(add-hook 'emacs-lisp-mode-hook 'linum-mode)
(require 'linum-relative)
;; Sets the value of curent line to be the actual line
(setq linum-relative-current-symbol "")

;;Make all my indentation using space and not tab
(setq-default indent-tabs-mode t)

(require 'flycheck)
(add-hook 'after-init-hook #'global-flycheck-mode)

;;; Start config of yasnippet and autocomplete
;;; makes them play nice together
;;;
(require 'yasnippet)
(yas-global-mode 1)
;;; auto complete mod
;;; should be loaded after yasnippet so that they can work together
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")
(ac-config-default)
;;; set the trigger key so that it can work together with yasnippet on tab key,
;;; if the word exists in yasnippet, pressing tab will cause yasnippet to
;;; activate, otherwise, auto-complete will
(ac-set-trigger-key "TAB")
(ac-set-trigger-key "<tab>")
;; end setup of yas and auto-complete

(global-rainbow-delimiters-mode)

